# Generated by Django 3.1.7 on 2021-03-08 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter your thoughts here.')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.blogger')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
